// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5472.TrackerTest.subsystems;

import org.usfirst.frc5472.TrackerTest.Robot;
import org.usfirst.frc5472.TrackerTest.RobotMap;
import org.usfirst.frc5472.TrackerTest.commands.JoystickDriveCommand;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriveSubsystem extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private final WPI_TalonSRX right = RobotMap.driveSubsystemRight;
	private final WPI_TalonSRX left = RobotMap.driveSubsystemLeft;
	private Solenoid gearMode = new Solenoid(0);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public void driver(double l, double r) {
		right.set(-r / 2);
		left.set(l / 2);
	}

	public void driveButton() {
		right.set(-0.5);
		left.set(0.5);

	}

	public void stopDrive() {
		right.set(0);
		left.set(0);
	}

	public double getLeft() {
		return left.get();
	}

	public double getRight() {
		return right.get();
	}

	public void shiftGear() {
		gearMode.set(!gearMode.get());
	}

	@Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		setDefaultCommand(new JoystickDriveCommand(Robot.getInstance().getOI().getJoystick1()));
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

}
